#!/usr/bin/env python3
"""Does the Type 1 font misnamed Yellowtail-Regular-TTF.sfd carry the shipped outlines?

Question answered: hg 52f780b apache/yellowtail/src/Yellowtail-Regular-TTF.sfd is a PFB
("%!PS-AdobeFont-1.0: Yellowtail 001.001", "%%CreationDate: Mon Jul 18 09:51:27 2011",
"Generated by FontForge 20110222", Creator Dave Crossland), not an SFD. The shipped TTF's
FFTM says FontForge 20110222 and sourceCreated = sourceModified = 2011-07-18 12:51:27 UTC.
Per codepoint, how close is the PFB's drawing to the shipped glyf (absolute area and
bounding box), compared with the designer's TTF (hg f66bfe1e9) and OTF, which Dave's
2011-07-18 FontForge session ("stripping hints and using the magic values", hg 60268f00f)
started from?

Usage:
  yellowtail_pfb_geometry.py            (reads everything from the archive / google/fonts)
Prints one line per candidate: counts of codepoints within 0.1% / 0.4% area, over 0.4%,
bbox within 1 unit, and the worst few.
"""
import io
import subprocess
import tempfile

from fontTools.pens.areaPen import AreaPen
from fontTools.pens.boundsPen import BoundsPen
from fontTools.t1Lib import T1Font
from fontTools.ttLib import TTFont

ARC = "/home/fsanches/compartilhado/upstream_repos/repo_archive/googlefonts/googlefontdirectory-hg.git"
GF = "/home/fsanches/compartilhado/google/fonts/apache/yellowtail/Yellowtail-Regular.ttf"


def blob(rev, path):
    return subprocess.run(["git", "-C", ARC, "show", "%s:%s" % (rev, path)], capture_output=True, check=True).stdout


def meas(glyph, gs):
    a, b = AreaPen(gs), BoundsPen(gs)
    glyph.draw(a)
    glyph.draw(b)
    return abs(a.value), b.bounds


def compare(label, shipped, get):
    gs, cm = shipped.getGlyphSet(), shipped.getBestCmap()
    n01 = n04 = over = bb1 = 0
    worst = []
    for cp, name in cm.items():
        a, ba = meas(gs[name], gs)
        r = get(cp, name)
        if r is None:
            continue
        b, bb = r
        if a == 0 and b == 0:
            continue
        rel = abs(a - b) / max(a, b)
        n01 += rel < 0.001
        n04 += 0.001 <= rel < 0.004
        over += rel >= 0.004
        bb1 += bool(ba and bb and max(abs(x - y) for x, y in zip(ba, bb)) <= 1)
        worst.append((round(rel * 100, 3), "U+%04X" % cp))
    worst.sort(reverse=True)
    print("%-38s area <0.1%%: %d, 0.1-0.4%%: %d, >=0.4%%: %d; bbox within 1 unit: %d; worst %s" % (
        label, n01, n04, over, bb1, worst[:4]))


def main():
    shipped = TTFont(GF)
    with tempfile.NamedTemporaryFile(suffix=".pfb") as fh:
        fh.write(blob("52f780bc9d197280a9f430574e179a5f233c56b6", "apache/yellowtail/src/Yellowtail-Regular-TTF.sfd"))
        fh.flush()
        t1 = T1Font(fh.name)
        t1.parse()
    cs = t1.font["CharStrings"]
    compare("PFB (misnamed -TTF.sfd)", shipped, lambda cp, n: meas(cs[n], cs) if n in cs else None)
    for label, path in (("designer TTF (hg f66bfe1e9)", "yellowtail/Yellowtail-Regular.ttf"),
                        ("designer OTF (hg f66bfe1e9)", "yellowtail/src/Yellowtail-Regular.otf")):
        f = TTFont(io.BytesIO(blob("f66bfe1e9", path)))
        g, c = f.getGlyphSet(), f.getBestCmap()
        compare(label, shipped, lambda cp, n, g=g, c=c: meas(g[c[cp]], g) if cp in c else None)


if __name__ == "__main__":
    main()
