#!/usr/bin/env python3
"""Write the pull-request body for a landed branch on a fork.

Question answered: what does a reviewer need to know about this branch? Derived
from the branch itself -- its commits and its convert commit's measured claim --
so the body cannot describe a different history from the one pushed.

Fresh repositories get no pull request (their first push creates `main`), so this
is for the forks and for a family added to an existing repository.

Output is ASCII, begins with the AI disclaimer, and is deliberately short.
Usage: pr_body.py <repo>        -> writes pr-bodies/<repo>.md
"""
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
W = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import land  # noqa: E402

DISCLAIMER = """> **Note**: This post was generated by an AI agent (Claude) working under the guidance of
> @felipesanches, but submitted **without human review**. @felipesanches himself would
> still need to participate in the PR thread if he wants to contribute to the review.
"""


def git(d, *a):
    return subprocess.run(["git", "-C", d, *a], capture_output=True, text=True, check=True).stdout


def main():
    repo = sys.argv[1]
    rows = land.family_rows(repo)
    kind = rows[0]["kind"]
    d = os.path.join(land.OUT, repo)
    base = "master" if kind == "allerta" else rows[0]["commit"]
    commits = git(d, "log", "--reverse", "--format=%h %s", "%s..HEAD" % base).splitlines()
    convert = git(d, "log", "-1", "--format=%B", "HEAD")
    claim = re.search(r"^(Builds with .*?)(?:\n\n|\Z)", convert, re.S | re.M)
    claim = " ".join(claim.group(1).split()) if claim else "(no build claim found)"
    names = sorted({land.display_name(r["family"]) for r in rows})
    lines = [DISCLAIMER]
    if kind == "allerta":
        lines.append("Adds Allerta Stencil, whose source this repository lost: the commit that "
                     "retired the legacy sources (2efd249) removed Allerta Stencil's `.sfd` too, "
                     "though only Allerta had been converted. The `.sfd` is restored byte-identical "
                     "to librefonts/allerta at the revision google/fonts records, then converted.\n")
    else:
        lines.append("Converts %s's FontForge sources to `.glyphs`, so the family builds with "
                     "gftools-builder and fontc.\n" % " and ".join(names))
    lines.append("One commit per step, the conversion last:\n")
    lines += ["- `%s`" % c for c in commits]
    lines.append("")
    lines.append(claim)
    lines.append("")
    lines.append("Every change made to the font before the conversion is its own commit; the "
                 "converted `.sfd` remains in the git history.")
    body = "\n".join(lines) + "\n"
    if any(ord(ch) > 127 for ch in body):
        sys.exit("FATAL: non-ASCII in the body")
    os.makedirs(os.path.join(W, "pr-bodies"), exist_ok=True)
    out = os.path.join(W, "pr-bodies", repo + ".md")
    open(out, "w").write(body)
    print(out)


if __name__ == "__main__":
    main()
